"""empty message

Revision ID: 9d4c8d500948
Revises: 7e495737c852
Create Date: 2020-12-21 02:12:43.159712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d4c8d500948'
down_revision = '7e495737c852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('venueeId', sa.Integer(), nullable=False),
    sa.Column('artistId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artistId'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['venueeId'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shows')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('venueeId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artistId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artistId'], ['Artist.id'], name='shows_artistId_fkey'),
    sa.ForeignKeyConstraint(['venueeId'], ['Venue.id'], name='shows_venueeId_fkey'),
    sa.PrimaryKeyConstraint('id', name='shows_pkey')
    )
    op.drop_table('Show')
    # ### end Alembic commands ###
